### PR TITLE
Add support for Vanilla 1.14

### PR DESCRIPTION
**Pull request by BrendanMcCallum**
Vanilla 1.14.2 server added from [server download page](https://www.minecraft.net/en-us/download/server/): https://launcher.mojang.com/v1/objects/808be3869e2ca6b62378f9f4b33c946621620019/server.jar

### CODE REVIEW

**Comment by KronK0321** [comment]
Hi, is this in the works?

**Comment by SilkAndSlug** [comment]
@benediktschmitt re. bug #79 . Are you still accepting pull-requests for new versions? v1.16 just came out, and EMSM's still on v1.13. I'm happy to help with the admin if you're happy to set that up.

**Comment by BrendanMcCallum** [comment]
I wouldn't consider #79 a bug.  Changing version numbers and adding links to new server jars and keep EMSM running the current version of Minecraft--while not entirely trivial--does not require refactoring.

I would be happy to collect PRs and continue to update my branch of EMSM, as @benediktschmitt seems to have abandoned all of their public projects. I do not use EMSM anymore, but I see the value in keeping it up to date and functional. I will try to contact them, in the hopes of either having my branch linked, this repo archived, the PYPI package transferred, or all of the above.

That said, the email @benediktschmitt lists is for their presently-defunct website, so this is the only place I know where to find them.  I will try to find another way.

**Comment by SilkAndSlug** [comment]
@BrendanMcCallum : if you're not using EMSM, you're probably not the best person to become the new maintainer -- though if you're able to contact @benediktschmitt , that would definitely be for the Greater Good! There are 17 Watchers and 25 Forks, so there are other possible maintainers; my own is now up to v1.15.2 f'instance.

**Comment by BrendanMcCallum** [comment]
@SilkAndSlug I'd be all for continuing to use EMSM, but I use papermc and haven't added support in my fork yet. (mainly I need to see how the backup functionality for spigot handles the multiple world's folder and copy that)

If I can get that up and running, I'd be more inclined to use EMSM, and I think papermc support would make it attractive to a wider userbase.

**Comment by benediktschmitt** [comment]
Hi, let's continue the maintenance discussion in #93.

-- Please excuse my long absence.

**Review by SilkAndSlug — APPROVED** [review]

**Pull request merged**
